Feature 186
ai-ecom/medusa-plugin-service pull request #31
Opened 2023-02-10 08:13 UTC by tholut

Done
- Add models, endpoints and service for default working breaks
- Add function V2 for merge default working hours with workingTimes

2023-02-10 11:22 UTC, akramaskar requested changes
Need some revision please.

2023-02-10 11:22 UTC, akramaskar commented on src/services/default-working-breaks.ts
> +      console.log(">> Create", rest);
Remove the console.logs please before merge

2023-02-10 11:22 UTC, akramaskar commented on src/services/default-working-breaks.ts
> +      console.log(">> Update", rest);
Same also here

2023-02-10 11:22 UTC, akramaskar commented on src/services/default-working-hour.ts
> +      const dateCurr = new Date(1000 * 24 * 60 * 60 * (dwh.day + 3));
why dwh.day + 3?

2023-02-10 11:22 UTC, akramaskar commented on src/services/default-working-hour.ts
> +      const blockedSlots = breaktime.map((bt) => ({ start: mergeMilitaryTimeWithDate(dateCurr, bt.from), end: mergeMilitaryTimeWithDate(dateCurr, bt.to)}))
Can you please add some comments here to explain your code?

2023-02-10 11:32 UTC, tholut commented on src/services/default-working-hour.ts
> +      const dateCurr = new Date(1000 * 24 * 60 * 60 * (dwh.day + 3));
It's because i want to get dateCurr from Sunday and currently unix timestamp is starting from Thursday

2023-02-13 14:09 UTC, akramaskar approved these changes

2023-02-13 14:09 UTC, merged